In [1]:
using Pkg

Pkg.activate("..")

using SymPy

In [2]:
#define params 2 consumers 1 resource
@syms x1,x2,y1
@syms u11,u21,R1,R2
@syms ρ1

dx1 = x1 * (y1 * u11 - R1)
dx2 = x2 * (y1 * u21 - R2)
dy1 = ρ1 - x1*u11*y1 - x2*u21*y1

nonlinsolve([dx1, subs(dy1,(x2,0))],y1,x1)

⎧⎛ R₁  ρ1⎞⎫
⎨⎜───, ──⎟⎬
⎩⎝u₁₁  R₁⎠⎭

In [3]:
#lyaponov
@syms a1,a2
V = a1*log(x1) + a2*log(x2)
dV = diff(V,x1) * dx1 + diff(V,x2) * dx2

a₁⋅(-R₁ + u₁₁⋅y₁) + a₂⋅(-R₂ + u₂₁⋅y₁)

In [4]:
#define constants
a1_ = 1/u11
a2_ = -1/u21

V_final = expand(subs(dV, (a1,a1_), (a2,a2_)))

Lt(V_final,0)

   R₁    R₂    
- ─── + ─── < 0
  u₁₁   u₂₁    

In [5]:
#2 consumers 2 resource
@syms y2, ρ2
@syms u12,u22

dx1 = x1 * (y1 * u11 + y2 * u12 - R1)
dx2 = x2 * (y1 * u21 + y2 * u22 - R2)
dy1 = 1 - x1*u11*y1 - x2*u21*y1
dy2 = 1 - x1*u12*y2 - x2*u22*y2

nonlinsolve([dx1, subs(dy1,(x2,0)), subs(dy2,(x2,0))],y1,y2,x1)

⎧⎛  R₁     R₁   2 ⎞⎫
⎨⎜─────, ─────, ──⎟⎬
⎩⎝2⋅u₁₁  2⋅u₁₂  R₁⎠⎭

In [6]:
V = a1*log(x1) + a2*log(x2)
dV = diff(V,x1) * dx1 + diff(V,x2) * dx2

a₁⋅(-R₁ + u₁₁⋅y₁ + u₁₂⋅y₂) + a₂⋅(-R₂ + u₂₁⋅y₁ + u₂₂⋅y₂)

In [76]:
#2 consumers 3 resource
@syms y3, ρ3
@syms u13,u23

dx1 = x1 * (y1 * u11 + y2 * u12 + y3 * u13 - R1)
dx2 = x2 * (y1 * u21 + y2 * u22 + y3 * u23 - R2)
dy1 = ρ1 - x1*u11*y1 - x2*u21*y1
dy2 = ρ2 - x1*u12*y2 - x2*u22*y2
dy3 = ρ3 - x1*u13*y3 - x2*u23*y3

nonlinsolve([dx1, subs(dy1,(x2,0)), subs(dy2,(x2,0)), subs(dy3,(x2,0))],y1,y2,y3,x1)

⎧⎛      R₁⋅ρ1               R₁⋅ρ2               R₁⋅ρ3         ρ1 + ρ2 + ρ3⎞⎫
⎨⎜──────────────────, ──────────────────, ──────────────────, ────────────⎟⎬
⎩⎝u₁₁⋅(ρ1 + ρ2 + ρ3)  u₁₂⋅(ρ1 + ρ2 + ρ3)  u₁₃⋅(ρ1 + ρ2 + ρ3)       R₁     ⎠⎭

In [77]:
V = a1*log(x1) + a2*log(x2)
dV = diff(V,x1) * dx1 + diff(V,x2) * dx2

a₁⋅(-R₁ + u₁₁⋅y₁ + u₁₂⋅y₂ + u₁₃⋅y₃) + a₂⋅(-R₂ + u₂₁⋅y₁ + u₂₂⋅y₂ + u₂₃⋅y₃)

In [78]:
ρtot = ρ1 + ρ2 + ρ3
a1_ = ρ1/(u11*ρtot) + ρ2/(u12*ρtot) + ρ3/(u13*ρtot)
a2_ = -(ρ1/(u21*ρtot) + ρ2/(u22*ρtot) + ρ3/(u23*ρtot))

V_final = subs(dV, (a1,a1_), (a2,a2_))

⎛        ρ3                   ρ2                   ρ1        ⎞                
⎜────────────────── + ────────────────── + ──────────────────⎟⋅(-R₁ + u₁₁⋅y₁ +
⎝u₁₃⋅(ρ1 + ρ2 + ρ3)   u₁₂⋅(ρ1 + ρ2 + ρ3)   u₁₁⋅(ρ1 + ρ2 + ρ3)⎠                

                    ⎛          ρ3                   ρ2                   ρ1   
 u₁₂⋅y₂ + u₁₃⋅y₃) + ⎜- ────────────────── - ────────────────── - ─────────────
                    ⎝  u₂₃⋅(ρ1 + ρ2 + ρ3)   u₂₂⋅(ρ1 + ρ2 + ρ3)   u₂₁⋅(ρ1 + ρ2 

     ⎞                                 
─────⎟⋅(-R₂ + u₂₁⋅y₁ + u₂₂⋅y₂ + u₂₃⋅y₃)
+ ρ3)⎠                                 

# Interactions

Here I derive a measure of interactions between species based on a given resource abundance. The general idea here is that given consumer $x_i(t)$ and resource $y_i(t)$ dynamics take the form:

\begin{align}
    \frac{dx_i(t)}{dt}  &= x_i(t) f_i(\vec{y}) \quad     \text{and,} \\
    \\
    \frac{dy_k(t)}{dt} &= g_k(\vec{x},\vec{y})
\end{align}

the effect of species $i$ on $j$ is given by:

\begin{align}
    a_{ij} = \sum_{k = 0}^M \frac{dg_k(\vec{x},\vec{y})}{dx_i(t)} \frac{df_j(\vec{y})}{dy_k(t)}
\end{align}

that is summing over all $M$ resources the effect of consumer $i$ on resource $k$ multiplied by the effect of resource $k$ on consumer $j$. This measure has nice properties such as maintaining the sign of interactions based on the effects of the two compontnets on the RHS:

|effect of i on k|effect of k on i|interaction|
|------|------|-----|
|+|+|+|
|+|0|0|
|-|+|-|
|-|0|0|

For the metabolic model the equations for growth are:

\begin{align}
    \frac{dx_i}{dt} = x_i \left[ \sum_{k=0}^M \left( y_k u_{ik} \left(1- \sum_{l=0}^M l_{kl}\right)\right) - R_i \right]
\end{align}

\begin{align}
    \frac{dy_k}{dt} = \rho_k - \sum_{i=0}^N x_i y_k u_{ik} + \sum_{i=0}^N \sum_{l=0}^M x_i y_l u_{il} l_{lk} 
\end{align}

which for a given $ij$ species pair interacting over resource $k$ gives:
\begin{align}
    a_{ij:k} =  \left[-y_k u_{ik} + \sum_{l=0}^M y_l u_{il} l_{lk}\right] \left[u_{jk} \left(1 - \sum_{l=0}^M l_{kl} \right)
    \right]
\end{align}

$$
    a_{ij:k} =  \left[-y_k u_{ik} \left[u_{jk} \left(1 - \sum_{l=0}^M l_{kl} \right)
    \right] + \sum_{l=0}^M y_l u_{il} l_{lk} \left[u_{jk} \left(1 - \sum_{l=0}^M l_{kl} \right)
    \right] \right] 
$$

$$
    a_{ij:k} =  -y_k u_{ik} u_{jk} \left(1 - l_{sum_{k}} \right) +
    \sum_{l=0}^M y_l u_{il} l_{lk} u_{jk} \left(1 - l_{sum_{k}} \right)
$$

$$
    a_{ij:k} =  -y_k u_{ik} u_{jk} \left(1 - l_{sum_{k}} \right) +
    M \left\langle y_l u_{il} l_{lk} u_{jk} \left(1 - l_{sum_{k}} \right) \right\rangle
$$

$$
    a_{ij:k} =  -y_k u_{ik} u_{jk} \left(1 - l_{sum_{k}} \right) +
    M \left\langle y_l u_{il} l_{lk} u_{jk} \left(1 - l_{sum_{k}} \right) \right\rangle
$$

In [57]:
y = [1 ; 1 ; 0.5]
u = [1 0 0.5 ; 0 0.5 1 ; 1 0 0]
l = [0.1 0.3 0.3; 0 0.3 0.3 ; 0 0 0.5]

y

3-element Vector{Float64}:
 1.0
 1.0
 0.5

In [70]:
u * (u * y)

3-element Vector{Float64}:
 1.75
 1.5
 1.25

In [75]:
y .* u[1,:] .* u[2,:] .* (1 .- sum(l, dims = 2 ))

3×1 Matrix{Float64}:
 0.0
 0.0
 0.125

In [54]:
function interaction(y,u,l,N,M)
    a = zeros(N,N)
    for i = 1:N
        for j = 1:N
            for k = 1:M
                a[i,j] -= y[k]*u[i,k]*u[j,k]*(1-l[k])
                for l = 1:M
                    a[i,j] += y[l] * u[i,l] * u[j,k] * l (1-l[k])
                end
            end
        end
    end
end


(0.0, 0.0, 0.25)

From this we can see the interaction is made up of two parts:
1. the Competition term: The amount of uptake of resource $k$ by species $i$, weighted by its uptake by species $j$

2. The Facilitation term: The amount of uptake of species $j$ (across all resources) that is leaked as resource $k$, again weighted by uptake by $j$